##########################
#    Plugin by lecson    #
#         Economy        #
#        moreMoney       #
##########################

#Money du server
money: "&f$"


#message de connection au server
joinserv:
  firstjoin: "&5Bienvenue&f, vous avez ouvert un nouveau compte de &5"
  join: "Bonjour ! Votre compte est de &5"


#message commande money (%a = prix)
message: "Votre compte est de &5 %a"


#message commande moneysee (%p = joueur %a = prix)
moneysee: "le compte de %p vaut &5"


#message /pay (%a = prix %p = joueur) !!! ne fonctionne que pour virementrecieve !!!
pay:
  soldeinf: "&3! &fVotre solde est insufisant &3!"
  virementok: "&eVotre virement est finis !"
  virementrecieve: "&eVous avez recu %a de la part de %p !"
  

#message erreur quand pas assez de block
shop:
  blocless: "&cpas assez de block !"
  

#############
#           #
#   Admin   #
#           #
#############


#message commande moneyset (%a = prix %p = joueur)
moneyset:
  add: "&eAjout de %a au joueur %p"
  sub: "&eRetrait de %a au joueur %p"
  set: "&eCompte de %p mis a %a"
  

#pas encore opérationel !!!!
jobs: "mineur,pecheur,boulanger,bucheron,chasseur,jardinier,macon"


#item shop (liste des nom d'items : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
mineur:
  item: "STONE,IRON_INGOT"
  nombre: "30,5"
  prix: "10,40"
pecheur:
  item: "STONE"
  nombre: "1"
  prix: "1"
boulanger:
  item: "STONE"
  nombre: "1"
  prix: "1"
bucheron:
  item: "STONE"
  nombre: "1"
  prix: "1"
chasseur:
  item: "STONE"
  nombre: "1"
  prix: "1"
jardinier:
  item: "STONE"
  nombre: "1"
  prix: "1"
macon:
  item: "STONE"
  nombre: "1"
  prix: "1"
  